#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

define('BASE_DIR', __DIR__);

$app = new Application();
$app->add(new \App\Command\Square());
$app->run();
